### ISSUE TITLE
New Devices - Chime 2nd Gen

### ISSUE THREAD

**Issue by robertalexa** [tsightler/ring-mqtt#168]
Hi,

I have been using your integration in parallel with the "official" one for a while now. Just wanted to thank you for your work :)

I have noticed that the Ring Chime is not supported, however it is available in the official integration.

Is this something you plan on doing any time soon? I have a Ring Chime 2nd Gen in my home and I would be glad to provide any info you need and test it for you in case this is something you do not currently have.

![image](https://user-images.githubusercontent.com/9019306/116590083-43b0ce00-a915-11eb-8a5f-bc691f9cf437.png)

I have attached what info there is in HA for the Chime with the default integration.

Personally I would love for this to be supported by your integration so I can uninstall the official one. I much prefer your work.

Looking forward to hearing from you.

Rob

**Comment by tsightler** [comment]
I'd love to support every Ring device, unfortunately, they have more devices than I have time!  :)

I don't have a Chime so can you help me understand what exactly you would like to see supported on it?  Is it just volume like in the screenshot or are there other functions that would be useful?

**Comment by robertalexa** [comment]
Hi again and thank you for your very prompt response.

For me personally, using the Ring app on my phone is a necessary evil, so because of that, any lacking features in HA would not be a killer.

But let me write down everything I can about this device, and then at least you know what you are looking at:
- Volume - just tested it now and the values are numbers ranging from 0 (mute) to 11 (i know it is weird, but it is deffo 11)
- WiFi Signal Category - not present on the phone App as words, but available in the Official Integration. Not entirely sure what the signal limits would be to define it.
- Signal Strength - also present in the phone app under device health as "RSSI - 44" where 44 is my current signal strength
- Network Name - not fussed
- there are also Chime Tones for Rings and Motion, but unless you can see them all in a selector in HA, and change them in HA, there is no point in just displaying it. I also don't really care that much about changing in from HA, but i guess it could be a nice feature.
- Device Name - i guess this is what you will use to name the device in HA
- Location - this is because Ring supports multi locations - probs irrelevant in the context of HA
- Status Light - in the app it is a toggle on/off - not sure if under the hood is 0/1 true/false or on/off or freaking unicorns (Ring are capable of all sorts haha)

This is literally everything visible in the Ring App for this device. Like said, if would be great to have "knowledge" of the device, the current volume and even setting it (in the same way you have handled the Base Station). WiFi Signal is a maybe (I have noticed that there is no entity for the Base Station either for this)

I hope this helps to understand what is available.

Let me know if there are any further tests you need me to run. I am more than happy to try to help.
The Chime device does not show up in the web browser so I can't sniff any network requests for you.

Offtopic: since I have mentioned the Base Station, it would be great if you would support the LED Settings (brightness). This device does show up in the web browser so I can send you more info if you need me to.

Best regards,
Rob

**Comment by tsightler** [comment]
I took a look at what the homebridge addon supports for chimes and it's the following:

Snooze for 24 hours or clear snooze
Play "Ding" sound
Play "Motion" sound
Adjust speaker volume

I could probably add all those for sure as they seem straightforward.  

If I'm looking at ring-client-api client, it doesn't appear to have support for heath status for chimes which I think would be required to get wifi status (it appears to work the same way as cameras, but simply not implemented in ring-client-api at this time, I could open an enhancement request on that project).

Would the features above be useful and sufficient?

**Comment by robertalexa** [comment]
Hi

The above sounds good.

You are right, i forgot to mention the snooze option. The potential values in the ring app are 1 3 6 9 12 hours.

All of the above sounds great. If the signal becomes available later that would be a great addition.

Thank you for your help
Rob

**Comment by tsightler** [comment]
@robertalexa Would you be willing to test the dev branch with your chime?  I have pushed a very first attempt at support with just the most basic of features (volume and snooze entitities).  It doesn't let you set anything right now but I'm mostly just wanting to know if the discovery works at all and if it reports valid data and changes to volume.  If this very basic stuff works then I think it shouldn't be too hard to add a few more things.

**Comment by robertalexa** [comment]
@tsightler apologies for coming back to you so late, life happened and i ran out of time for hobbies :)

Yes that is ok, i will do my best to find time and test this for you.

**Comment by robertalexa** [comment]
@tsightler Hi again, just got everything sorted on my testing HA instance and unfortunately the Chime doesn't seem to be discovered? Initially i thought this is because i didn't enable cameras, but i have ended up including everything and still no luck.

Here is my config
```
enable_cameras: true
snapshot_mode: all
enable_modes: false
enable_panic: false
beam_duration: 0
disarm_code: '0000'
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
branch: dev
ring_token: ''
location_ids:
  - ''
enable_volume: true
```

Here are all the discovered devices:
![image](https://user-images.githubusercontent.com/9019306/127303963-459244fe-a7a1-4aa1-96e3-9921f67eea39.png)

And finally here is a dump of the logs:


I hope this helps you,
Rob

LE: collapse the logs as they were making the page huuuge

**Comment by tsightler** [comment]
Thanks @robertalexa, I see what I need to do.  As chimes are their own category and need to add a call to pull in Chime devices into the array of discovered devices similar to how I handle cameras.  Should be an easy change, I'll try to address it tonight.

**Comment by robertalexa** [comment]
sounds good. drop me a message when you need me to test. now that i have the development HA up and running it should be a simple case of restarting the addon so i an do that whenever, thanks for your input

**Comment by tsightler** [comment]
@robertalexa I took another stab at it since it seemed really easy.  I'm not 100% sure what I did was enough, but if you could give it a quick spin it would be really useful.  At a minimum it should provide me with better logs!

**Comment by robertalexa** [comment]
@tsightler the device is now found but it is not discovered by HA.

This is the only reference about it in the logs
`2021-07-28T14:53:30.219Z ring-mqtt   New device: Downstairs (chime_v2, 50738195),`

**Comment by tsightler** [comment]
OK, well, that's got me stumped for now.  I'm struggling to theorize how it's even possible that the device was found but not published.  I'm guessing it has to be something with the location Id, but I'll have to dig a little bit or maybe add some debugging in the chime code.

**Comment by tsightler** [comment]
@robertalexa  I pushed a new version that will hopefully spit out some debug info that will be enough for me to continue if you can get logs when you have a chance.  I think it's something silly, but I need to be sure.

**Comment by robertalexa** [comment]
@tsightler 

I have redacted some personal information out of the log.

**Comment by tsightler** [comment]
OK, I think that was enough for me to figure out what was happening.  Hopefully we'll now at least get some discovery packets being sent.

**Comment by robertalexa** [comment]
The device is still not discovered in HA

**Comment by tsightler** [comment]
OK, stupid error that time, tried out a new technique to store topic and had some silly errors, but at least it actually tried to publish the device this time.  I've removed the debug since that part is clearly working.  I'm hopeful this will work now but if not, I'm probably done for today since clearly my head is not in it.  :)

**Comment by robertalexa** [comment]
@tsightler The device is now discovered but getting 2 errors, at least 1 of them being fatal and breaking everything past it - that meaning all the discovered devices become unavailable.

First error is:
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'command' of undefined,
    at Chime.initDiscoveryData (/app/ring-mqtt-dev/devices/chime.js:104:50),
    at Chime.publish (/app/ring-mqtt-dev/devices/chime.js:39:58),
    at /app/ring-mqtt-dev/ring-mqtt.js:202:28,
    at Array.forEach (<anonymous>),
    at publishDevices (/app/ring-mqtt-dev/ring-mqtt.js:200:25),
(Use `node --trace-warnings ...` to show where the warning was created),
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
```

And then the fatal:
```
2021-07-29T07:31:49.429Z ring-mqtt Exit code: TypeError: Cannot read property 'state' of undefined,
```

Here is the discovered device:
![image](https://user-images.githubusercontent.com/9019306/127451692-ff8192b8-c545-49cf-80c9-f942c34119b9.png)

**Comment by tsightler** [comment]
@robertalexa Thank you again for your patience.  The first error was a typo, but the second one has me stumped.  With no stack trace to know where it is coming from I searched for every use of 'state' and none seem like they should be an issue.

**Comment by tsightler** [comment]
@robertalexa So I decided to just order a chime pro rather than continue to subject you to my poor coding skills.  When it comes it next week I'll pick this back up and hopefully have something in a few weeks.

**Comment by robertalexa** [comment]
@tsightler No worries and no stressing about it. Thank you though for looking into it. Let me know if you need me to test anything at a later date.

**Comment by tsightler** [comment]
4.7.0 has been release with support for the following Ring Chime features:

Volume Control
Play ding/motion sounds
Enter/Exit Snooze Mode
Set Snooze Minute (must be set prior to entering snooze state)
Wireless Signal in dBm (Wireless network name in attributes)
Device info sensor with detailed state information such as (exact info varies by device):
Wireless Signal
Wired Network Name
Firmware Status
Last Update Status

Other features such as controlling the nightlight or status light might be added in the future if the commands for controlling them are discovered.
