### ISSUE TITLE
All sensors are Unavailable despite correct Ring authentication and device discovery

### ISSUE THREAD

**Issue by thunder2k** [tsightler/ring-mqtt#332]
#### Describe the problem
All sensors created by this add-on are unavailable

##### Describe your environment
Installed via ring-mqtt-ha-addon

#### Describe any steps you've taken to attempt to resolve the problem
Switch enable_cameras to true and snapshot_mode to motion

#### Debug Logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] ring-mqtt.sh: executing... 
-------------------------------------------------------
| Ring-MQTT with Video Streaming                      |
| Addon for Home Assistant                            |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
[cont-init.d] ring-mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
-------------------------------------------------------
ring-mqtt.js version: 4.9.1
Node version v16.13.2
NPM version 8.1.3
git version 2.34.1
-------------------------------------------------------
Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
-------------------------------------------------------
Running ring-mqtt...
2022-02-27T14:47:13.294Z ring-mqtt Using configuration file: /data/options.json
2022-02-27T14:47:13.305Z ring-mqtt Reading latest data from state file: /data/ring-state.json
2022-02-27T14:47:13.593Z ring-mqtt Attempting connection to Ring API using saved refresh token.
2022-02-27T14:47:14.545Z ring-mqtt Connection to Ring API successful
2022-02-27T14:47:14.554Z ring-mqtt Starting connection to MQTT broker...
2022-02-27T14:47:14.780Z ring-mqtt File /data/ring-state.json saved with updated refresh token.
2022-02-27T14:47:14.810Z ring-mqtt MQTT connection established, processing locations...
2022-02-27T14:47:16.709Z ring-mqtt --------------------------------------------------------------------------------
2022-02-27T14:47:16.712Z ring-mqtt New location: XXXX (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
2022-02-27T14:47:16.726Z ring-mqtt   New device: Front Door (xxxxxxxxxxxx)
2022-02-27T14:47:16.727Z ring-mqtt               doorbell_v4
2022-02-27T14:47:16.732Z ring-mqtt   New device: Living Room (xxxxxxxxxxxx)
2022-02-27T14:47:16.732Z ring-mqtt               chime
2022-02-27T14:47:16.733Z ring-mqtt --------------------------------------------------------------------------------
2022-02-27T14:47:16.733Z ring-mqtt Ring location/device data updated, sleeping for 5 seconds.
2022-02-27T14:53:48.438Z ring-rtsp -------------------------------------------------------------------------
2022-02-27T14:53:48.438Z ring-rtsp Starting rtsp-simple-server process...
2022-02-27T14:53:48.852Z ring-rtsp INF rtsp-simple-server v0.17.13
2022-02-27T14:53:48.854Z ring-rtsp INF [RTSP] listener opened on 0.0.0.0:8554 (TCP)
2022-02-27T14:53:48.855Z ring-rtsp INF [API] listener opened on 127.0.0.1:8880
2022-02-27T14:53:49.606Z ring-rtsp Creating RTSP paths for all cameras...
2022-02-27T14:53:49.645Z ring-rtsp INF [API] [conn 127.0.0.1:54176] POST /v1/config/paths/add/xxxxxxxxxxxx_live
2022-02-27T14:53:49.659Z ring-rtsp INF reloading configuration (API request)
2022-02-27T14:53:49.681Z ring-rtsp INF [API] [conn 127.0.0.1:54178] POST /v1/config/paths/add/xxxxxxxxxxxx_event
2022-02-27T14:53:49.683Z ring-rtsp INF reloading configuration (API request)
2022-02-27T14:53:49.789Z ring-rtsp -------------------------------------------------------------------------
Then it starts describing all the topics..

**Comment by tsightler** [comment]
Based on the logs the only possible conclusion is something within your MQTT setup, either permissions or a failure of configuration for the MQTT client receiving the messages.  Unfortunately, I don't have time to provide support for things outside of ring-mqtt itself, which is clearly working in your case, so you should double check your configuration, perhaps check with an MQTT client to see the messages.

**Comment by thunder2k** [comment]
> Based on the logs the only possible conclusion is something within your MQTT setup, either permissions or a failure of configuration for the MQTT client receiving the messages. Unfortunately, I don't have time to provide support for things outside of ring-mqtt itself, which is clearly working in your case, so you should double check your configuration, perhaps check with an MQTT client to see the messages.

Hi,
Thanks a lot for your answer, it pointed me in the right direction and, in fact, the auto-discovered MQTT credentials were wrong, hence it was failing. After setting the correct MQTT credentials in the addon settings, it started working!

**Comment by jamesphw** [comment]
I'm not sure if it's related to a recent update, but I also found the <auto_detect> settings for MQTT stopped working, and all sensors became unavailable.

I fixed this by manually creating credentials for ring-mqtt in mostquito broker, and configuring ring-mqtt to use those credentials.

**Comment by tsightler** [comment]
There's no way this can be related to any updates, the code for this is super simple and leverages the internal HA API to acquire the MQTT authentication information.  This code hasn't changed in quite a long time.  I've, very occasionally, seen this API fail during addon startup, but a restart of HA should fix that issue.

Other than that, the other common reason for requiring manual configuration is any time users do any manual configuration of the Mosquitto addon/integration.  Basically, once you do any manual configuration, the odds of auto detect working drop significantly.

However, I know it mostly works because, any time it has broken in the past, it's lead to dozens of posts in short order and, on top of that, I ONLY use automatic configuration in my production and development instances because, realistically, I know that expecting most users to get that right is a support nightmare and I'd probably have already ended this project if it wasn't for Home Assistants automatic MQTT configuration.

**Comment by jamesphw** [comment]
Yes, its almost certainly not a bug ring-mqtt, but it could be related to a recent HA update (possibly a bug in core). In the last couple of months I think I've only updated the core parts of HA, with no configuration changes or upgrades to either ring-mqtt or mosquito. And restarting HA didn't solve the problem for me either. It was a tough one to solve.

Anyhow, this thread helped solve my issues, so perhaps if anyone else encounters the same problem the manual configuration for mqtt is the way to go.

**Comment by VeniceNerd** [comment]
Hi @jamesphw I have a similar issue. I noticed that all of my Ring Motion Sensors and Window Sensor are suddenly showing as "unavailable". The doorbells and chimes are still online, though. All my other MQTT devices are still working as well. It is just the Ring Motion Sensors and Contact Sensors that are showing as unavailable.

I have not made any updates to my HA system in months, though. I am still on the following:

Home Assistant 2022.12.7
Supervisor 2023.03.1 (this seems like it somehow updated automatically?)
Operating System 9.4
Frontend 20221213.1 - latest

My Ring MQTT is on version 5.0.5

Do you think this issue could be related to yours? If so do you have any pointers on how I could check?

Thank you!

**Comment by tsightler** [comment]
You are responding to a post from over a year ago, it's unlikely the issue is related, although 99% of issues can be resolved by simply restarting HA fully (not the restore in the UI, but a full reboot) or by restarting the addon.  Also, ring-mqtt does not keep any secrets, the logs contain every action, including online/offline events, connects/disconnects to Ring or MQTT, etc.  Feel free to open a new thread or issue, but be prepared to provide the required log information.

**Comment by VeniceNerd** [comment]
You already fixed it. The full restart did the trick. Dang. Thanks!
________________________________
