### ISSUE TITLE
live camera is allways on since 2022.05.02 update

### ISSUE THREAD

**Issue by divemasterjm** [tsightler/ring-mqtt#363]
Sin las ha update live camera is allways on, even if i stop stream with switch turn off, switch is automatically turned on.
in the log i have constantly this lines.

2022-05-11T07:14:03.922Z ring-rtsp INF [RTSP] [conn 172.30.32.1:37834] opened
2022-05-11T07:14:03.925Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started
2022-05-11T07:14:03.932Z ring-rtsp [Puerta principal] Sending command to activate live stream ON-DEMAND
2022-05-11T07:14:03.941Z ring-mqtt [Puerta principal] Received set live stream state ON-DEMAND
2022-05-11T07:14:13.926Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command stopped
2022-05-11T07:14:13.926Z ring-rtsp INF [RTSP] [conn 172.30.32.1:37834] closed (source of path '50f14af94113_live' has timed out)
2022-05-11T07:14:13.927Z ring-rtsp [Puerta principal] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-05-11T07:14:13.929Z ring-mqtt [Puerta principal] Received set live stream state OFF
2022-05-11T07:14:13.929Z ring-mqtt [Puerta principal] Stopping live stream session on workerId 1

**Comment by divemasterjm** [comment]
I did more troubleshooting, if i disable generic camera, stops switching on, must be something with new integration on ui with generic cameras i think
no luck, still switchin on
022-05-11T07:55:29.397Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started
2022-05-11T07:55:29.412Z ring-rtsp [Puerta principal] Sending command to activate live stream ON-DEMAND
2022-05-11T07:55:29.428Z ring-mqtt [Puerta principal] Received set live stream state ON-DEMAND
2022-05-11T07:55:29.428Z ring-mqtt [Puerta principal] ring/cfa12cc8-09cd-4b6e-90ea-1053516457f6/camera/50f14af94113/stream/state ON
2022-05-11T07:55:29.429Z ring-attr [Puerta principal] ring/cfa12cc8-09cd-4b6e-90ea-1053516457f6/camera/50f14af94113/stream/attributes {"status":"activating"}
2022-05-11T07:55:29.430Z ring-mqtt [Puerta principal] Starting a live stream session via Ring servers
2022-05-11T07:55:29.480Z ring-rtsp [Puerta principal] State indicates live stream is activating
2022-05-11T07:55:29.982Z ring-mqtt [Puerta principal] Live stream assigned to worker 1 with 0 current active sessions

**Comment by tsightler** [comment]
The trigger for starting a live stream is unchanged from previous versions, a live stream will start when a client connects to the RTSP server which, based on the logs in your original post, is clearly happening in your case:

> 2022-05-11T07:14:03.922Z ring-rtsp INF [RTSP] [conn 172.30.32.1:37834] opened
> 2022-05-11T07:14:03.925Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started

I have no way to know what is connecting, but clearly there is a connection to the RTSP server, which correctly runs the on-demand script to start the live stream.

Remember that Home Assistant generic camera will not timeout for 5 mintues after any viewing in the frontend.  Even if you manually stop the stream Home Assistant will just wait 10 seconds and reconnect (this was a change in behavior in Home Assistant some months ago) and it will continue trying to reconnect until the 5 minute timeout passes.  Each time you view the stream in the frontend the timeout is reset.

**Comment by divemasterjm** [comment]
> The trigger for starting a live stream is unchanged from previous versions, a live stream will start when a client connects to the RTSP server which, based on the logs in your original post, is clearly happening in your case:
> 
> > 2022-05-11T07:14:03.922Z ring-rtsp INF [RTSP] [conn 172.30.32.1:37834] opened
> > 2022-05-11T07:14:03.925Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started
> 
> I have no way to know what is connecting, but clearly there is a connection to the RTSP server, which correctly runs the on-demand script to start the live stream.
> 
> Remember that Home Assistant generic camera will not timeout for 5 mintues after any viewing in the frontend. Even if you manually stop the stream Home Assistant will just wait 10 seconds and reconnect (this was a change in behavior in Home Assistant some months ago) and it will continue trying to reconnect until the 5 minute timeout passes. Each time you view the stream in the frontend the timeout is reset.

as far as i know i dont have any client starting the connection, i remove camera config and is still happening, very weird cause i dont know where to start looking for.
can you give me some advise to search for?

**Comment by tsightler** [comment]
> [conn 172.30.32.1:37834] opened

The fact that it is coming from 172.30.32.1, which is the internal IP address of the Home Assistant instance, implies that something running on Home Assistant is connecting to the RTSP server.  I have no way to know what you have installed.  My guess is some addon or custom integration, or perhaps the HA media player or automatic discovery process, that is finding the RTSP server and trying to connect to it.

Have you followed the advice in the FAQ and set a username/password for the livestream?  That way, at least only items you have explicitly configured with the correct username/password could possibly connect.

**Comment by divemasterjm** [comment]
I will try to put user and Pw, but I think I've found it, I think it is homekit integration cause I expose the live stream camero to hk. I delete it 10min ago and I had no request to start it, strange cause is not new setup, I did it long time ago, maybe hk integration is working different since last update. Anyway I will set up user/Pw just in case.

Thanks for your help

**Comment by tsightler** [comment]
Honestly, for Homekit integration with Ring you'd be better off running Homebridge or Scrypted vs gatewaying from ring-mqtt to Homekit via Home Assistant (if I understood correctly your setup), but hopefully you have found the source.

**Comment by divemasterjm** [comment]
> Honestly, for Homekit integration with Ring you'd be better off running Homebridge or Scrypted vs gatewaying from ring-mqtt to Homekit via Home Assistant (if I understood correctly your setup), but hopefully you have found the source.

too fast, even with usr/password, and no cameras yet defined, live stream is started, as you can see, no errors even i set up user/pw

2022-05-11T17:37:28.044Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command stopped
2022-05-11T17:37:28.045Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41808] closed (source of path '50f14af94113_live' has timed out)
2022-05-11T17:37:28.045Z ring-rtsp [Puerta principal] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-05-11T17:37:28.051Z ring-mqtt [Puerta principal] Received set live stream state OFF
2022-05-11T17:37:28.051Z ring-mqtt [Puerta principal] Stopping live stream session on workerId 1
2022-05-11T17:37:29.844Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41880] opened
2022-05-11T17:37:29.853Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41880] closed (EOF)
2022-05-11T17:37:40.068Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41940] opened
2022-05-11T17:37:40.080Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started
2022-05-11T17:37:40.082Z ring-rtsp [Puerta principal] Sending command to activate live stream ON-DEMAND
2022-05-11T17:37:40.085Z ring-mqtt [Puerta principal] Received set live stream state ON-DEMAND
2022-05-11T17:37:50.081Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command stopped
2022-05-11T17:37:50.081Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41940] closed (source of path '50f14af94113_live' has timed out)
2022-05-11T17:37:50.082Z ring-rtsp [Puerta principal] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-05-11T17:37:50.092Z ring-mqtt [Puerta principal] Received set live stream state OFF
2022-05-11T17:37:50.092Z ring-mqtt [Puerta principal] Stopping live stream session on workerId 1
2022-05-11T17:38:12.360Z ring-rtsp INF [RTSP] [conn 172.30.32.1:42044] opened
2022-05-11T17:38:12.362Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command started
2022-05-11T17:38:12.364Z ring-rtsp [Puerta principal] Sending command to activate live stream ON-DEMAND
2022-05-11T17:38:12.368Z ring-mqtt [Puerta principal] Received set live stream state ON-DEMAND
2022-05-11T17:38:22.363Z ring-rtsp INF [path 50f14af94113_live] runOnDemand command stopped
2022-05-11T17:38:22.364Z ring-rtsp INF [RTSP] [conn 172.30.32.1:42044] closed (source of path '50f14af94113_live' has timed out)
2022-05-11T17:38:22.365Z ring-rtsp [Puerta principal] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)

**Comment by divemasterjm** [comment]
@tsightler i’ve found the problem, it seems the switch is not working, I had to turn it OFF  via MQTT explorer manually and the problem is solved. Also I’ve found ding is detecting as movement and viceversa, is like they are changed.Can you have a look on it?
Thanks

**Comment by tsightler** [comment]
I'm sorry, but I don't have any idea what this even means.  MQTT Explorer would only send the very same command Home Assistant is sending.  I have no problems using the switch within Home Assistant.  To this point you've provided nearly zero logs, but the minimal logs you have provided clearly show a client connecting to the RTSP server.  No matter what you do with the switch, if a client connects to the RTSP server, the stream will start again. and the switch will turn back on.

**Comment by divemasterjm** [comment]
> I'm sorry, but I don't have any idea what this even means.  MQTT Explorer would only send the very same command Home Assistant is sending.  I have no problems using the switch within Home Assistant.  To this point you've provided nearly zero logs, but the minimal logs you have provided clearly show a client connecting to the RTSP server.  No matter what you do with the switch, if a client connects to the RTSP server, the stream will start again. and the switch will turn back on.

And what about ding and movement sensors? Now I receive ding instead of movement

**Comment by tsightler** [comment]
> And what about ding and movement sensors? Now I receive ding instead of movement

What about them?  They still exist.  Ding and motion are separate sensors as they always have been.  Did you upgrade to 5.x of ring-mqtt and, if so, did you read the change logs and breaking changes documentation as requested?

Are you saying you are somehow receiving motion events on the ding sensor?  Again, without logs and some additional details this isn't very productive, if you continue to fail to deliver this information, which is clearly requested when opening an issue, I'm not sure how to help you.

**Comment by divemasterjm** [comment]
> > And what about ding and movement sensors? Now I receive ding instead of movement
> 
> 
> 
> What about them?  They still exist.  Ding and motion are separate sensors as they always have been.  Did you upgrade to 5.x of ring-mqtt and, if so, did you read the change logs and breaking changes documentation as requested?
> 
> 
> 
> Are you saying you are somehow receiving motion events on the ding sensor?  Again, without logs and some additional details this isn't very productive, if you continue to fail to deliver this information, which is clearly requested when opening an issue, I'm not sure how to help you.

Yes I mean I'm receiving motion events on ding sensor, please tell me all you need and I will forward you

**Comment by tsightler** [comment]
I have 7 cameras of several different models and I've tested this pretty extensively, but perhaps there is something unexpected going on with the push notifications (which are a change by the underlying API, not really in ring-mqtt).  By any chance do you not have a Ring Protect Plan?  Do you have rich notifications enabled?  I need the [full addon logs](https://github.com/tsightler/ring-mqtt-ha-addon/blob/master/GET-LOGS.md), but, at a minimum, I need the logs when a motion event occurs and the version of ring-mqtt you are running.

I'm going to close this issue with the streaming since you say that is resolved and this issue is different and unrelated.  Please open a new issue, describe the behavior clearly and in detail, and provide the requested logs and version information.
